language: node_js
node_js:
  - '0.12'

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DEPLOY_BRANCH=master
  - GH_REF=github.com/developmentseed/satsummit.git
  - secure: "cCtSHOHhie8qTELIatgiKC1ADHMRjayztpAvLJuAJ2Ux9rqigI2uCH3OEfLPK5WlZiE/YLnEGe1PtHZkbiLiuNRSjaxXamz6ec5ftp2OZ7vto3MH8fBtnBs6zXh9GWZUuzq3IDFrbCEpNSQGicTSlCsMXUvJziann08Txp0eVEIqG8Hdb2uUzDlIXXox7nuLxRxVx2v34knCeIk0O/Ehe0aTQFxDl38k5hWA0dCyrMmRt9HL2gYCj3ciNgjhoA4UksOvW5PcqZVfefvRSqxw482TJyJnzA70nAcdoypUA8qOuO9h2xHFog6Duag7Pxq5RVdIeeZm2HOVLf7mUFrZqaE9qhQfmagFxq2OOq0WTZtNJFajh9XFAniBccS10SLNLmBaDvb5YOMSwlcvJIootaSnHgEIyoeuR4LXgkYXEGOWWJ+S0DLhkBlWVMESWXaLONtyVnRgTWXSuwlhDOw48YZsQLfhW+kM3+SR6BFl+eo8pd7lBB92bpGpxEv+P2+qkTenxTxrGXKcNi+4aCbdBdELNZexyo5YHlorCQooeJ+Cg+ldk5JPc7PylobCrn76tz7pzSiZW77x5+oyBwI/gU1tg2zmyrO9t/yBy5ZaaoZjrxhDM5hUhcknaPuNPhlpAvxQR/VRHxSVdf+EX/iaJbL5ORiKGGgo4aacwGv7M2I="
  
cache:
  directories:
    - node_modules
    - bundle/cache

before_install:
  - chmod +x ./.build_scripts/build.sh
  - chmod +x ./.build_scripts/deploy.sh

script:
  - travis_wait ./.build_scripts/build.sh

after_success:
  - travis_wait ./.build_scripts/deploy.sh