source: source
# To exclude inside source/
exclude:
  - assets/scripts
  - assets/styles
  - assets/graphics/collecticons
baseurl: http://localhost:3000
kramdown:
  input: GFM
  syntax_highlighter: rouge

##
# Default values
##
defaults:
  -
    scope:
      type: events
    values:
      layout: event
  -
    scope:
      type: speakers
    values:
      layout: speaker

##
# Collections definitions
##
collections:
  events:
    output: true
    permalink: /agenda/:slug/
  speakers:
    output: true
    permalink: /speakers/:path/
  sponsors:
    output: false
