source: source
# To exclude inside source/
exclude:
  - assets/scripts
  - assets/styles
  - assets/graphics/collecticons
baseurl: https://satsummit.io
permalink: /insights/:year/:month/:day/:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge

##
# Global definitions
##
event_date: 2017-01-31

##
# Default values
##
defaults:
  -
    scope:
      type: posts
    values:
      layout: insights-single
  -
    scope:
      type: events
    values:
      layout: events-single
  -
    scope:
      type: speakers
    values:
      layout: speakers-single

##
# Collections definitions
##
collections:
  events:
    output: true
    permalink: /agenda/:slug/
  speakers:
    output: true
    permalink: /speakers/:path/
  sponsors:
    output: false
