# Site settings
title: Satellite Summit
email: satellite@mapbox.com
url: http://devseed.com/satsummit
description: "Nullam quis risus eget urna mollis ornare vel eu leo. Curabitur blandit tempus porttitor."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'
